In [1]:
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.metrics import r2_score

C:\Users\MY\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df=pd.read_csv('final_data.csv')

In [3]:
df.head()

Date  compound    neg    neu    pos   Close
0  3-Jan-11   -0.8934  0.172  0.746  0.082  119.49
1  4-Jan-11   -0.6996  0.133  0.806  0.060  121.87
2  5-Jan-11   -0.9442  0.319  0.638  0.044  124.93
3  6-Jan-11   -0.7906  0.179  0.726  0.094  124.98
4  7-Jan-11   -0.5859  0.140  0.766  0.094  124.99

In [4]:
X=df[['compound','neg','neu','pos']]
# X=df[['neg','neu','pos']]
# Y=df[['Close']]/400     #normalize it
Y=df[['Close']]

In [5]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33)

In [6]:
from sklearn import preprocessing
min_max_scalar=preprocessing.MinMaxScaler()
X_train=min_max_scalar.fit_transform(X_train)
X_test=min_max_scalar.fit_transform(X_test)
Y_train=min_max_scalar.fit_transform(Y_train)
Y_test=min_max_scalar.fit_transform(Y_test)

In [7]:
# from sklearn.preprocessing import StandardScaler
# scalar=StandardScaler()
# scalar.fit(X_train)
# X_train=scalar.transform(X_train)
# X_test=scalar.transform(X_test)

In [8]:
from keras.models import Sequential
from keras.layers import Dense
from keras import losses
from keras import activations

C:\Users\MY\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [9]:
model=Sequential()

In [10]:
model.add(Dense(4,activation=activations.sigmoid,input_shape=(4,)))
# model.add(Dense(3,activation='relu',input_shape=(3,)))
model.add(Dense(100,activation=activations.sigmoid))
model.add(Dense(100,activation=activations.sigmoid))
model.add(Dense(100,activation=activations.sigmoid))
model.add(Dense(100,activation=activations.sigmoid))
model.add(Dense(100,activation=activations.sigmoid))
model.add(Dense(1,activation=activations.sigmoid))

In [11]:
model.compile(optimizer='adam',loss=losses.mean_absolute_error)

In [12]:
# while 1:
#     model.fit(X_train,Y_train,epochs=500)
#     y_pred=model.predict(X_test)
#     falto=r2_score(Y_test,y_pred)
#     print(falto)
#     if falto >= 70.0:
#         break

In [13]:
model.fit(X_train,Y_train,verbose=2)

Epoch 1/1
 - 2s - loss: 0.2012


In [14]:
y_pred=model.predict(X_test)

In [15]:
print(r2_score(Y_test,y_pred))

-0.00386725945672195


In [16]:
-11.1517567590531

-11.1517567590531

In [17]:
y_pred

array([[0.36261585],
       [0.36261624],
       [0.36261544],
       [0.36261553],
       [0.36261532],
       [0.36261535],
       [0.36261407],
       [0.36261466],
       [0.36261508],
       [0.3626079 ],
       [0.36261564],
       [0.36261305],
       [0.3626158 ],
       [0.36261454],
       [0.36260906],
       [0.3626162 ],
       [0.36261553],
       [0.362616  ],
       [0.36261645],
       [0.36261502],
       [0.3626132 ],
       [0.3626164 ],
       [0.362615  ],
       [0.36261418],
       [0.3626071 ],
       [0.362616  ],
       [0.36261475],
       [0.362615  ],
       [0.3626126 ],
       [0.36261502],
       [0.36261505],
       [0.3626156 ],
       [0.36261502],
       [0.36261567],
       [0.36261588],
       [0.36261553],
       [0.36261645],
       [0.36261475],
       [0.36261508],
       [0.36261535],
       [0.3626162 ],
       [0.362616  ],
       [0.36261463],
       [0.3626156 ],
       [0.3626158 ],
       [0.36261582],
       [0.3626132 ],
       [0.362

In [18]:
Y_test

array([[0.56583436],
       [0.77727748],
       [0.74725974],
       [0.57461227],
       [0.53804521],
       [0.57211079],
       [0.03588484],
       [0.12866694],
       [0.5698822 ],
       [0.28826125],
       [0.52244508],
       [0.39691636],
       [0.50297903],
       [0.11620503],
       [0.45194888],
       [0.43166417],
       [0.03747669],
       [0.64024196],
       [0.47018693],
       [0.5865284 ],
       [0.80201938],
       [0.56046755],
       [0.08509574],
       [0.1287579 ],
       [0.03515714],
       [0.36175922],
       [0.16446082],
       [0.06908628],
       [0.14708691],
       [0.11611407],
       [0.63278301],
       [0.54814208],
       [0.13862737],
       [0.46982308],
       [0.66052667],
       [0.08027471],
       [0.32692045],
       [0.10569882],
       [0.49915859],
       [0.00582162],
       [0.38404512],
       [0.03552099],
       [0.41820166],
       [0.40523946],
       [0.39054896],
       [0.13166871],
       [0.34979761],
       [0.502

In [19]:
model.evaluate(X_train,Y_train)

1236/1236 [==============================] - 0s 156us/step


0.19464584702812737

In [20]:
model.evaluate(X_test,Y_test)

610/610 [==============================] - 0s 84us/step


0.20041663363331655

In [21]:
model.evaluate(X_test,y_pred)

610/610 [==============================] - 0s 113us/step


0.0

In [22]:
model.layers[0].get_weights()

[array([[-0.39439338,  0.7394769 ,  0.5976062 ,  0.10832803],
        [-0.53737074,  0.37399262, -0.07217079,  0.05122531],
        [-0.14279613, -0.00128876, -0.2621399 , -0.40994066],
        [-0.28114653, -0.8427895 , -0.0926476 , -0.30379266]],
       dtype=float32),
 array([ 0.00716783,  0.00444512, -0.00157858,  0.00503871], dtype=float32)]

In [23]:
model.layers[0].get_weights()[0]

array([[-0.39439338,  0.7394769 ,  0.5976062 ,  0.10832803],
       [-0.53737074,  0.37399262, -0.07217079,  0.05122531],
       [-0.14279613, -0.00128876, -0.2621399 , -0.40994066],
       [-0.28114653, -0.8427895 , -0.0926476 , -0.30379266]],
      dtype=float32)

In [24]:
model.layers[0].get_weights()[1]

array([ 0.00716783,  0.00444512, -0.00157858,  0.00503871], dtype=float32)

In [25]:
model.layers[1].get_weights()

[array([[-3.51308808e-02,  1.37427554e-01,  8.61495137e-02,
         -5.00481054e-02,  8.09336677e-02, -9.90257487e-02,
         -7.77051598e-03, -2.08359942e-01, -7.12438971e-02,
         -1.33776609e-02, -3.11051570e-02, -1.34025827e-01,
         -4.47479486e-02, -2.29659751e-01, -2.20070258e-01,
         -9.39633027e-02,  5.96366338e-02, -2.07440093e-01,
         -6.59536645e-02, -1.63992450e-01,  5.20012975e-02,
          4.79112230e-02,  1.01685397e-01, -1.33690506e-01,
         -2.84030549e-02,  1.44623816e-01,  1.04679562e-01,
         -5.59668727e-02, -1.52170047e-01, -1.85068205e-01,
         -2.13647187e-01,  1.19612113e-01, -2.70911958e-02,
         -1.01417571e-01,  1.00411803e-01, -1.64378226e-01,
          1.60933450e-01,  5.07001057e-02,  6.34711981e-02,
          2.41953228e-02, -1.16329998e-01, -1.52777359e-02,
          2.01189458e-01, -1.78290933e-01, -9.05183330e-02,
          7.75006413e-02, -6.47120178e-02, -1.61095902e-01,
          4.11125919e-04, -1.77928552e-0

In [26]:
model.layers

In [27]:
len(model.layers[2].get_weights()[0])

100

In [28]:
min_max_scalar.inverse_transform(y_pred)

array([[168.42834],
       [168.42844],
       [168.42825],
       [168.42828],
       [168.42822],
       [168.42824],
       [168.42795],
       [168.42809],
       [168.42818],
       [168.4266 ],
       [168.4283 ],
       [168.42773],
       [168.42833],
       [168.42805],
       [168.42685],
       [168.42842],
       [168.42828],
       [168.42838],
       [168.42847],
       [168.42816],
       [168.42776],
       [168.42847],
       [168.42816],
       [168.42798],
       [168.42642],
       [168.42838],
       [168.4281 ],
       [168.42816],
       [168.42763],
       [168.42816],
       [168.42818],
       [168.42828],
       [168.42816],
       [168.4283 ],
       [168.42836],
       [168.42828],
       [168.42847],
       [168.4281 ],
       [168.42818],
       [168.42824],
       [168.42842],
       [168.42838],
       [168.42809],
       [168.42828],
       [168.42833],
       [168.42834],
       [168.42776],
       [168.42847],
       [168.42834],
       [168.42819],


In [29]:
y_pred

array([[0.36261585],
       [0.36261624],
       [0.36261544],
       [0.36261553],
       [0.36261532],
       [0.36261535],
       [0.36261407],
       [0.36261466],
       [0.36261508],
       [0.3626079 ],
       [0.36261564],
       [0.36261305],
       [0.3626158 ],
       [0.36261454],
       [0.36260906],
       [0.3626162 ],
       [0.36261553],
       [0.362616  ],
       [0.36261645],
       [0.36261502],
       [0.3626132 ],
       [0.3626164 ],
       [0.362615  ],
       [0.36261418],
       [0.3626071 ],
       [0.362616  ],
       [0.36261475],
       [0.362615  ],
       [0.3626126 ],
       [0.36261502],
       [0.36261505],
       [0.3626156 ],
       [0.36261502],
       [0.36261567],
       [0.36261588],
       [0.36261553],
       [0.36261645],
       [0.36261475],
       [0.36261508],
       [0.36261535],
       [0.3626162 ],
       [0.362616  ],
       [0.36261463],
       [0.3626156 ],
       [0.3626158 ],
       [0.36261582],
       [0.3626132 ],
       [0.362